### ISSUE TITLE
Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by alicescfernandes** [GoogleChromeLabs/estimator.dev#13]
Trying to run EStimator here:
https://estimator.dev/#observador.pt

The request to the /check completes with data, but while parsing that data the code breaks
![image](https://user-images.githubusercontent.com/15971182/102015595-7b4b1f00-3d54-11eb-8adf-44987136e50d.png)

**Comment by guidezpl** [comment]
Same error with [flutter.dev](https://flutter.dev). Also, once an error like this occurs, the search bar becomes non-functional

**Comment by developit** [comment]
this should be fixed now!
